"""
Generated command-line help specification.

Do not edit by hand. Regenerate from:

    <reference-executable> --help | python make_help_spec.py llama_bench_help_spec.py
"""

from __future__ import annotations

from typing import Any

HELP_SPEC: dict[str, Any] = {'program': 'llama-bench',
 'usage': 'usage: llama-bench [options]',
 'sections': {'options': [{'aliases': ['-h', '--help'],
                           'primary': '--help',
                           'takes_value': False,
                           'value_hint': None,
                           'choices': None,
                           'default': None,
                           'description': ''},
                          {'aliases': ['--numa'],
                           'primary': '--numa',
                           'takes_value': True,
                           'value_hint': '<distribute|isolate|numactl>',
                           'choices': ['distribute', 'isolate', 'numactl'],
                           'default': 'disabled',
                           'description': 'numa mode (default: disabled)'},
                          {'aliases': ['-r', '--repetitions'],
                           'primary': '--repetitions',
                           'takes_value': True,
                           'value_hint': '<n>',
                           'choices': None,
                           'default': '5',
                           'description': 'number of times to repeat each test (default: 5)'},
                          {'aliases': ['--prio'],
                           'primary': '--prio',
                           'takes_value': True,
                           'value_hint': '<-1|0|1|2|3>',
                           'choices': ['-1', '0', '1', '2', '3'],
                           'default': '0',
                           'description': 'process/thread priority (default: 0)'},
                          {'aliases': ['--delay'],
                           'primary': '--delay',
                           'takes_value': True,
                           'value_hint': '<0...N> (seconds)',
                           'choices': None,
                           'default': '0',
                           'description': 'delay between each test (default: 0)'},
                          {'aliases': ['-o', '--output'],
                           'primary': '--output',
                           'takes_value': True,
                           'value_hint': '<csv|json|jsonl|md|sql>',
                           'choices': ['csv', 'json', 'jsonl', 'md', 'sql'],
                           'default': 'md',
                           'description': 'output format printed to stdout (default: md)'},
                          {'aliases': ['-oe', '--output-err'],
                           'primary': '--output-err',
                           'takes_value': True,
                           'value_hint': '<csv|json|jsonl|md|sql>',
                           'choices': ['csv', 'json', 'jsonl', 'md', 'sql'],
                           'default': 'none',
                           'description': 'output format printed to stderr (default: none)'},
                          {'aliases': ['--list-devices'],
                           'primary': '--list-devices',
                           'takes_value': False,
                           'value_hint': None,
                           'choices': None,
                           'default': None,
                           'description': 'list available devices and exit'},
                          {'aliases': ['-v', '--verbose'],
                           'primary': '--verbose',
                           'takes_value': False,
                           'value_hint': None,
                           'choices': None,
                           'default': None,
                           'description': 'verbose output'},
                          {'aliases': ['--progress'],
                           'primary': '--progress',
                           'takes_value': False,
                           'value_hint': None,
                           'choices': None,
                           'default': None,
                           'description': 'print test progress indicators'},
                          {'aliases': ['--no-warmup'],
                           'primary': '--no-warmup',
                           'takes_value': False,
                           'value_hint': None,
                           'choices': None,
                           'default': None,
                           'description': 'skip warmup runs before benchmarking'},
                          {'aliases': ['-fitt', '--fit-target'],
                           'primary': '--fit-target',
                           'takes_value': True,
                           'value_hint': '<MiB>',
                           'choices': None,
                           'default': 'off',
                           'description': 'fit model to device memory with this margin per device in MiB (default: '
                                          'off)'},
                          {'aliases': ['-fitc', '--fit-ctx'],
                           'primary': '--fit-ctx',
                           'takes_value': True,
                           'value_hint': '<n>',
                           'choices': None,
                           'default': '4096',
                           'description': 'minimum ctx size for --fit-target (default: 4096)'}],
              'test_parameters': [{'aliases': ['-m', '--model'],
                                   'primary': '--model',
                                   'takes_value': True,
                                   'value_hint': '<filename>',
                                   'choices': None,
                                   'default': 'models/7B/ggml-model-q4_0.gguf',
                                   'description': '(default: models/7B/ggml-model-q4_0.gguf)'},
                                  {'aliases': ['-hf', '-hfr', '--hf-repo'],
                                   'primary': '--hf-repo',
                                   'takes_value': True,
                                   'value_hint': '<user>/<model>[:quant] Hugging Face model repository; quant is '
                                                 'optional, case-insensitive',
                                   'choices': None,
                                   'default': 'unused',
                                   'description': ' default to Q4_K_M, or falls back to the first file in the repo if '
                                                  "Q4_K_M doesn't exist. example: ggml-org/GLM-4.7-Flash-GGUF:Q4_K_M "
                                                  '(default: unused)'},
                                  {'aliases': ['-hff', '--hf-file'],
                                   'primary': '--hf-file',
                                   'takes_value': True,
                                   'value_hint': '<file>',
                                   'choices': None,
                                   'default': 'unused',
                                   'description': 'Hugging Face model file. If specified, it will override the quant '
                                                  'in --hf-repo (default: unused)'},
                                  {'aliases': ['-hft', '--hf-token'],
                                   'primary': '--hf-token',
                                   'takes_value': True,
                                   'value_hint': '<token>',
                                   'choices': None,
                                   'default': 'value from HF_TOKEN environment variable',
                                   'description': 'Hugging Face access token (default: value from HF_TOKEN environment '
                                                  'variable)'},
                                  {'aliases': ['--offline'],
                                   'primary': '--offline',
                                   'takes_value': False,
                                   'value_hint': None,
                                   'choices': None,
                                   'default': 'disabled',
                                   'description': 'Offline mode: forces use of cache, prevents network access '
                                                  '(default: disabled)'},
                                  {'aliases': ['-p', '--n-prompt'],
                                   'primary': '--n-prompt',
                                   'takes_value': True,
                                   'value_hint': '<n>',
                                   'choices': None,
                                   'default': '512',
                                   'description': '(default: 512)'},
                                  {'aliases': ['-n', '--n-gen'],
                                   'primary': '--n-gen',
                                   'takes_value': True,
                                   'value_hint': '<n>',
                                   'choices': None,
                                   'default': '128',
                                   'description': '(default: 128)'},
                                  {'aliases': ['-pg'],
                                   'primary': '-pg',
                                   'takes_value': True,
                                   'value_hint': '<pp,tg>',
                                   'choices': None,
                                   'default': '',
                                   'description': '(default: )'},
                                  {'aliases': ['-d', '--n-depth'],
                                   'primary': '--n-depth',
                                   'takes_value': True,
                                   'value_hint': '<n>',
                                   'choices': None,
                                   'default': '0',
                                   'description': '(default: 0)'},
                                  {'aliases': ['-b', '--batch-size'],
                                   'primary': '--batch-size',
                                   'takes_value': True,
                                   'value_hint': '<n>',
                                   'choices': None,
                                   'default': '2048',
                                   'description': '(default: 2048)'},
                                  {'aliases': ['-ub', '--ubatch-size'],
                                   'primary': '--ubatch-size',
                                   'takes_value': True,
                                   'value_hint': '<n>',
                                   'choices': None,
                                   'default': '512',
                                   'description': '(default: 512)'},
                                  {'aliases': ['-ctk', '--cache-type-k'],
                                   'primary': '--cache-type-k',
                                   'takes_value': True,
                                   'value_hint': '<t>',
                                   'choices': None,
                                   'default': 'f16',
                                   'description': '(default: f16)'},
                                  {'aliases': ['-ctv', '--cache-type-v'],
                                   'primary': '--cache-type-v',
                                   'takes_value': True,
                                   'value_hint': '<t>',
                                   'choices': None,
                                   'default': 'f16',
                                   'description': '(default: f16)'},
                                  {'aliases': ['-t', '--threads'],
                                   'primary': '--threads',
                                   'takes_value': True,
                                   'value_hint': '<n>',
                                   'choices': None,
                                   'default': '6',
                                   'description': '(default: 6)'},
                                  {'aliases': ['-C', '--cpu-mask'],
                                   'primary': '--cpu-mask',
                                   'takes_value': True,
                                   'value_hint': '<hex,hex>',
                                   'choices': None,
                                   'default': '0x0',
                                   'description': '(default: 0x0)'},
                                  {'aliases': ['--cpu-strict'],
                                   'primary': '--cpu-strict',
                                   'takes_value': True,
                                   'value_hint': '<0|1>',
                                   'choices': ['0', '1'],
                                   'default': '0',
                                   'description': '(default: 0)'},
                                  {'aliases': ['--poll'],
                                   'primary': '--poll',
                                   'takes_value': True,
                                   'value_hint': '<0...100>',
                                   'choices': None,
                                   'default': '50',
                                   'description': '(default: 50)'},
                                  {'aliases': ['-ngl', '--n-gpu-layers'],
                                   'primary': '--n-gpu-layers',
                                   'takes_value': True,
                                   'value_hint': '<n>',
                                   'choices': None,
                                   'default': '-1',
                                   'description': '(default: -1)'},
                                  {'aliases': ['-ncmoe', '--n-cpu-moe'],
                                   'primary': '--n-cpu-moe',
                                   'takes_value': True,
                                   'value_hint': '<n>',
                                   'choices': None,
                                   'default': '0',
                                   'description': '(default: 0)'},
                                  {'aliases': ['-sm', '--split-mode'],
                                   'primary': '--split-mode',
                                   'takes_value': True,
                                   'value_hint': '<none|layer|row|tensor>',
                                   'choices': ['none', 'layer', 'row', 'tensor'],
                                   'default': 'layer',
                                   'description': '(default: layer)'},
                                  {'aliases': ['-mg', '--main-gpu'],
                                   'primary': '--main-gpu',
                                   'takes_value': True,
                                   'value_hint': '<i>',
                                   'choices': None,
                                   'default': '0',
                                   'description': '(default: 0)'},
                                  {'aliases': ['-nkvo', '--no-kv-offload'],
                                   'primary': '--no-kv-offload',
                                   'takes_value': True,
                                   'value_hint': '<0|1>',
                                   'choices': ['0', '1'],
                                   'default': '0',
                                   'description': '(default: 0)'},
                                  {'aliases': ['-fa', '--flash-attn'],
                                   'primary': '--flash-attn',
                                   'takes_value': True,
                                   'value_hint': '<on|off|auto>',
                                   'choices': ['on', 'off', 'auto'],
                                   'default': 'auto',
                                   'description': '(default: auto)'},
                                  {'aliases': ['-dev', '--device'],
                                   'primary': '--device',
                                   'takes_value': True,
                                   'value_hint': '<dev0/dev1/...>',
                                   'choices': None,
                                   'default': 'auto',
                                   'description': '(default: auto)'},
                                  {'aliases': ['-mmp', '--mmap'],
                                   'primary': '--mmap',
                                   'takes_value': True,
                                   'value_hint': '<0|1>',
                                   'choices': ['0', '1'],
                                   'default': '1',
                                   'description': '(default: 1)'},
                                  {'aliases': ['-dio', '--direct-io'],
                                   'primary': '--direct-io',
                                   'takes_value': True,
                                   'value_hint': '<0|1>',
                                   'choices': ['0', '1'],
                                   'default': '0',
                                   'description': '(default: 0)'},
                                  {'aliases': ['-embd', '--embeddings'],
                                   'primary': '--embeddings',
                                   'takes_value': True,
                                   'value_hint': '<0|1>',
                                   'choices': ['0', '1'],
                                   'default': '0',
                                   'description': '(default: 0)'},
                                  {'aliases': ['-ts', '--tensor-split'],
                                   'primary': '--tensor-split',
                                   'takes_value': True,
                                   'value_hint': '<ts0/ts1/..>',
                                   'choices': None,
                                   'default': '0',
                                   'description': '(default: 0)'},
                                  {'aliases': ['-ot', '--override-tensor'],
                                   'primary': '--override-tensor',
                                   'takes_value': True,
                                   'value_hint': '<tensor name pattern>=<buffer type>;...',
                                   'choices': None,
                                   'default': 'disabled',
                                   'description': ' (default: disabled)'},
                                  {'aliases': ['-nopo', '--no-op-offload'],
                                   'primary': '--no-op-offload',
                                   'takes_value': True,
                                   'value_hint': '<0|1>',
                                   'choices': ['0', '1'],
                                   'default': '0',
                                   'description': '(default: 0)'},
                                  {'aliases': ['--no-host'],
                                   'primary': '--no-host',
                                   'takes_value': True,
                                   'value_hint': '<0|1>',
                                   'choices': ['0', '1'],
                                   'default': '0',
                                   'description': '(default: 0)'}]},
 'notes': ["Multiple values can be given for each parameter by separating them with ','",
           'or by specifying the parameter multiple times. Ranges can be given as',
           "'first-last' or 'first-last+step' or 'first-last*mult'."]}
